kibot:
  version: 1

globals:
  resources_dir: resources
  field_lcsc_part: "LCSC"
  solder_mask_color: blue
  pcb_finish: ENIG

filters:
  - name: only_jlc_parts
    comment: "Only parts with JLC (LCSC) code"
    type: generic
    include_only:
      - column: "LCSC"
        regex: '^C\d+'

variants:
  - name: rotated
    comment: "Rotate for JLCPCB"
    type: kibom
    variant: rotated
    pre_transform: _rot_footprint_jlcpcb

outputs:
  - name: "report"
    comment: "Generates a report about the design."
    type: "report"
    dir: "report"
    options:
      converted_output: "%f-%i%I%v.%x"
      eurocircuits_class_target: "3B"
      eurocircuits_reduce_holes: 0
      template: "kibot/custom_full_report.txt"
      do_convert: true
      convert_to: "pdf"

  - name: "pdf_sch_print_default"
    type: "pdf_sch_print"
    dir: "Schematic"
    options:
      all_pages: true
      monochrome: false
      output: "%f-%i%I%v-default.%x"
  - name: "pdf_sch_print_mono"
    type: "pdf_sch_print"
    dir: "Schematic"
    options:
      all_pages: true
      monochrome: true
      output: "%f-%i%I%v-mono.%x"

  - name: JLCPCB_gerbers
    comment: Gerbers compatible with JLCPCB
    type: gerber
    dir: JLCPCB/Gerber
    options: &gerber_options
      exclude_edge_layer: true
      exclude_pads_from_silkscreen: true
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: false
      force_plot_invisible_refs_vals: false
      tent_vias: true
      use_protel_extensions: true
      create_gerber_job_file: false
      disable_aperture_macros: true
      gerber_precision: 4.6
      use_gerber_x2_attributes: false
      use_gerber_net_attributes: false
      line_width: 0.1
      subtract_mask_from_silk: true
    layers:
      # Note: a more generic approach is to use 'copper' but then the filenames
      # are slightly different.
      - F.Cu
      - B.Cu
      - F.Paste
      - B.Paste
      - F.SilkS
      - B.SilkS
      - F.Mask
      - B.Mask
      - Edge.Cuts

  - name: JLCPCB_drill
    comment: Drill files compatible with JLCPCB
    type: excellon
    dir: JLCPCB/Drill
    options:
      pth_and_npth_single_file: false
      pth_id: "-PTH"
      npth_id: "-NPTH"
      metric_units: true
      map: gerber
      route_mode_for_oval_holes: false
      output: "%f%i.%x"

  - name: JLCPCB
    comment: ZIP file for JLCPCB
    type: compress
    dir: JLCPCB
    options:
      files:
        - from_output: JLCPCB_gerbers
          dest: /
        - from_output: JLCPCB_drill
          dest: /

  - name: "JLCPCB_position"
    comment: "Pick and place file, JLCPCB style"
    type: position
    dir: JLCPCB/PickAndPlace
    options:
      variant: rotated
      output: "%f_cpl_jlc.%x"
      format: CSV
      units: millimeters
      separate_files_for_front_and_back: false
      only_smd: false
      columns:
        - id: Ref
          name: Designator
        - Val
        - Package
        - id: PosX
          name: "Mid X"
        - id: PosY
          name: "Mid Y"
        - id: Rot
          name: Rotation
        - id: Side
          name: Layer

  - name: "JLCPCB_bom"
    comment: "BoM for JLCPCB"
    type: bom
    dir: JLCPCB/BOM
    options:
      output: "%f_%i_jlc.%x"
      exclude_filter: "only_jlc_parts"
      ref_separator: ","
      columns:
        - field: Value
          name: Comment
        - field: References
          name: Designator
        - Footprint
        - field: "LCSC"
          name: "LCSC #"
        - field: "Quantity Per PCB"
          name: "QTY"
      csv:
        hide_pcb_info: true
        hide_stats_info: true
        quote_all: true

  - name: ibom
    comment: Interactive BOM
    type: ibom
    dir: IBOM
    options:
      dark_mode: true
      name_format: "index"
      include_tracks: true
      show_fields: "Value,Footprint,Datasheet,LCSC"

  - name: "Markdown components table"
    comment: "All LCSC components in HTML"
    type: bom
    dir: BOM
    options:
      output: "%f_%i.%x"
      exclude_filter: "only_jlc_parts"
      columns:
        - field: Value
          name: Value
        - field: References
          name: Reference
        - Footprint
        # - field: MFN
        #   name: "Manufacturer"
        # - field: MPN
        #   name: "Manufacturer Part Number"
        - Datasheet
        - Sheetpath
        - field: "LCSC"
          name: "LCSC #"
        - field: "Quantity Per PCB"
          name: "Quantity"
      format: "HTML"
      html:
        datasheet_as_link: "Datasheet"
        lcsc_link: true

  - name: "Info"
    comment: "Records information about the current run."
    type: "info"
    dir: "CI"
    options:
      environment: "names"
      output: "%f-%i%I%v.%x"
