name: "KiBot Build"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '*.md'
      - '.github/**'
  pull_request:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '*.md'
      - '.github/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  kibot:
    uses: ./.github/workflows/build-project.yml
    with:
      PROJECT_NAME: "hextrack"
      PROJECT_PATH: "hardware/electrical/"
      RENDER_ACTION_ID: 12683041655

  build:
    runs-on: ubuntu-latest
    needs: [
      kibot
    ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            _includes
            _layouts
            _sass
            assets

      - name: Artifacts for hextrack
        uses: tmshader/hextrack/.github/artifacts@main
        with:
          PROJECT_NAME: "hextrack"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        if: always()
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
          future: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4